### PR TITLE
Improve perf in the push_bits() and get_bits() functions

### PR DESCRIPTION
**Pull request by jcdubois**
Also remove some compilation warnings.

With these patches, on my old core m5, I can double the compression performance (at least on some big files).

### CODE REVIEW

**Comment by silentbicycle** [comment]
Thanks. I'm really busy at the moment but will look this over more closely within the next few weeks.

**Comment by jcdubois** [comment]
I also added a possible perf improvement for get_bits() in the decoder.

**Comment by jcdubois** [comment]
One thing that is a bit surprising is that get_bits is never called with a "count" > 8. The comment in the function states that it could be called with count up to 15. But when running "make test" or "make bench" this (a count between 9 and 15) is never triggered. Is there an explanation?

**Comment by silentbicycle** [comment]
Could you re-target this to the `develop` branch? `master` should really be named `release`, I do versioned releases merging from `develop`. It's mentioned right at the top of `CONTRIBUTING.md`.

**Comment by jcdubois** [comment]
I have already done it in pull request #80.

**Comment by jcdubois** [comment]
This sound like a mess. I am going to make something cleaner.

**Pull request closed without merging**
